version: '3'

services:
  quarkus-app:
    image: robinthedev/quarkus-app
    build:
      dockerfile: quarkusapp/src/main/docker/Dockerfile.jvm
    ports:
      - 8000:8080
  spring-app:
    image: robinthedev/spring-app
    build:
      dockerfile: springapp/src/main/docker/Dockerfile.jvm
    ports:
      - 8001:8080
  prometheus:
    image: prom/prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data: