FROM registry.access.redhat.com/ubi8/openjdk-17:1.14

ENV LANGUAGE='en_US:en'


# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 springapp/target/spring-run.jar /deployments/

EXPOSE 8080
USER 185

ENV JAVA_APP_JAR="/deployments/spring-run.jar"

